<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC35Jz7R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC35Jz7R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC35Jz7R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC35Jz7R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC35Jz7R\App_KernelDevDebugContainer([
    'container.build_hash' => 'C35Jz7R',
    'container.build_id' => 'b1ee523b',
    'container.build_time' => 1591871919,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC35Jz7R');
